### ISSUE TITLE
Crash after 2nd launch (click on 'practice')

### ISSUE THREAD

**Issue by tenzap** [machiav3lli/DerDieDas#12]
with v2.0 from f-droid:

First launch, I use it a little bit to learn, then quit the app, then relaunch the app.
At that time, when clicking on  "practice" there is a crash.

device: xiaomi redmi note 9s with android 10

logcat says: 

```
d84
07-15 15:24:26.739 21457 21457 I chatty  : uid=10356(com.machiav3lli.derdiedas) identical 15 lines
07-15 15:24:26.739 21457 21457 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.machiav3lli.derdiedas activity: com.machiav3lli.derdiedas.ui.WordActivity@47cbd84
07-15 15:24:26.743 21457 21457 D AndroidRuntime: Shutting down VM
07-15 15:24:26.752 21457 21457 E AndroidRuntime: FATAL EXCEPTION: main
07-15 15:24:26.752 21457 21457 E AndroidRuntime: Process: com.machiav3lli.derdiedas, PID: 21457
07-15 15:24:26.752 21457 21457 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at java.util.ArrayList.get(ArrayList.java:437)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at com.machiav3lli.derdiedas.ui.WordFragment.O0(Unknown Source:21)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at androidx.fragment.app.Fragment.n1(Unknown Source:4)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at androidx.fragment.app.s.f(Unknown Source:261)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at androidx.fragment.app.s.m(Unknown Source:116)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at androidx.fragment.app.l.d0(Unknown Source:277)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at androidx.fragment.app.l.Z0(Unknown Source:84)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at androidx.fragment.app.l.a0(Unknown Source:21)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at androidx.fragment.app.l.S(Unknown Source:42)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at androidx.fragment.app.l.y(Unknown Source:11)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at androidx.fragment.app.g.c(Unknown Source:4)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at androidx.fragment.app.d.onStart(Unknown Source:15)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at androidx.appcompat.app.c.onStart(Unknown Source:0)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at com.machiav3lli.derdiedas.ui.WordActivity.onStart(Unknown Source:0)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:7923)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3332)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:224)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7562)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
07-15 15:24:26.752 21457 21457 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
07-15 15:24:26.758  1664  4651 W ActivityTaskManager:   Force finishing activity com.machiav3lli.derdiedas/.ui.WordActivity
07-15 15:24:26.758  1664 21511 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
07-15 15:24:26.759  1664  4651 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
07-15 15:24:26.761  1664  4651 W ActivityTaskManager:   Force finishing activity com.machiav3lli.derdiedas/.ui.MainActivity
07-15 15:24:26.763 32437  2492 D Launcher: get showing item successnull
0
```

**Comment by machiav3lli** [comment]
Yes, I can reproduce it. I'll get to it when I can
