### ISSUE TITLE
[bug] Crash on wrong answer

### ISSUE THREAD

**Issue by chromer030** [machiav3lli/DerDieDas#46]
But it's OK and keep going on true answers.

Android : 7.1.2 arm64

![Screenshot_20230928-185443](https://github.com/machiav3lli/DerDieDas/assets/13361552/437107de-fd6d-43ca-ae1c-c9cd12ffcea3)

**Comment by zekooooo** [comment]
Same here on Android 7.0

**Comment by machiav3lli** [comment]
Crashlogs? You may use something like Scoop or LogFox to catch it

**Comment by machiav3lli** [comment]
Please test [this build](https://upload.disroot.org/r/9PL5LBTQ#K6wkLwy2eiwKbfkMOOg4C9x4MI7Q5XaX5kZug88k6oc=)

**Comment by caralu74** [comment]
I have the same trouble, I've tested with another Webview, and with and other one, but none of them work. So for now I downgrade the app and work fine, for now.

**Comment by opk12** [comment]
Hello, I copied the log from the [LogFox](https://f-droid.org/en/packages/com.f0x1d.logfox/) notification on Samsung Android 7.1. Unfortunately, the phone owner only allows F-droid builds. 2.2.0 crashes. 2.1.0 and 2.1.1 do **not** crash.

```
FATAL EXCEPTION: DefaultDispatcher-worker-3
Process: com.machiav3lli.derdiedas, PID: 26755
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7988)
	at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1392)
	at android.view.ViewGroup.invalidateChild(ViewGroup.java:5426)
	at android.view.View.invalidateInternal(View.java:14975)
	at android.view.View.invalidate(View.java:14911)
	at android.view.View.invalidateDrawable(View.java:19241)
	at android.widget.TextView.invalidateDrawable(TextView.java:6379)
	at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:439)
	at android.graphics.drawable.RippleDrawable.invalidateSelf(RippleDrawable.java:714)
	at android.graphics.drawable.RippleDrawable.invalidateSelf(RippleDrawable.java:710)
	at android.graphics.drawable.LayerDrawable.invalidateDrawable(LayerDrawable.java:996)
	at android.graphics.drawable.DrawableWrapper.invalidateDrawable(DrawableWrapper.java:205)
	at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:439)
	at android.graphics.drawable.LayerDrawable.invalidateDrawable(LayerDrawable.java:996)
	at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:439)
	at c2.h.setTintList(SourceFile:8)
	at y.b.h(SourceFile:1)
	at com.google.android.material.button.MaterialButton.setSupportBackgroundTintList(SourceFile:28)
	at com.google.android.material.button.MaterialButton.setBackgroundTintList(SourceFile)
	at m2.a.k(SourceFile:1)
	at s2.a.b(SourceFile:1)
	at f3.b0.run(SourceFile:1)
	at kotlinx.coroutines.scheduling.a.run(SourceFile:77)
	Suppressed: f3.z: [f1{Cancelling}@ee72c6f, Dispatchers.Default]
```
